spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://comparatordb.cichvuqweebz.eu-central-1.rds.amazonaws.com:5432/comparator
    username: comparator
    password: dbReset503